### ISSUE TITLE
Report: Units w/ 0 admin

### ISSUE THREAD

**Issue by justingonder** [eScholarship/jschol#720]
@alainna was able to produce a [report](https://docs.google.com/spreadsheets/d/1F7ybGXaBJYnnW1AfGa6eSdywApqptzeNT0aFk3Jec3I/edit?usp=sharing) on units with admins whose account have the bounce flag set.

Now I also need a report of units that have no user with an admin role associated with them. It would be helpful to have the same headers in this new report as Alainna provided in hers: Campus | Unit Name | Unit ID | eScholarship URL | Status.

Need this by 9/10/2024 to prep for an eScholarship Liaisons meeting. In that meeting we aim to make our campus liaisons aware of abandoned eScholarship units and to enlist their help in identifying a) the actual status of the unit (i.e. is it truly a moribund entity) and b) a potential replacement admin.

**Comment by myucekul** [comment]
@justingonder - I'm looking into DB to find out where we store the admin info. Is there an example of unit with and one without admin that you can share.

**Comment by myucekul** [comment]
[unitreport.csv](https://github.com/user-attachments/files/16937010/unitreport.csv)

**Comment by myucekul** [comment]
@justingonder - please take a look at the csv and let me know if you need anything else.

**Comment by justingonder** [comment]
thanks @myucekul - this looks to be what i need, i'm just surprised how few of them there are (which is, perhaps, a good thing!)
